services:
  - type: web
    name: dev-db
    env: docker
    plan: free
    dockerCommand: "docker compose up dev-db -d"
    dockerfilePath: ./docker-compose.yml
    envVars:
      - key: DATABASE_URL
        fromService:
          type: web
          name: Fiu-Fit-users-service
          envVarKey: DATABASE_URL

  - type: web
    name: test-db
    plan: free
    env: docker
    dockerCommand: "docker compose up test-db -d"
    dockerfilePath: ./docker-compose.yml
    envVars:
      - key: DATABASE_URL
        fromService:
          type: web
          name: Fiu-Fit-users-service
          envVarKey: DATABASE_URL


