version: "3.9"
services:
  db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiu-fit-users
    networks:
      - fiu-fit
  test-db:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiu-fit-users-test
    networks:
      - fiu-fit
networks:
  fiu-fit:
