version: "3.9"
services:
  db:
    image: postgres
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiu-fit-service-registry
    networks:
      - fiu-fit
  test-db:
    image: postgres
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiu-fit-service-registry-test
    networks:
      - fiu-fit
networks:
  fiu-fit:
