version: "3.9"
services:
  db:
    image: postgres
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiu-fit-progress
    networks:
      - fiu-fit
  test-db:
    image: postgres
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiu-fit-progress-test
    networks:
      - fiu-fit
networks:
  fiu-fit:
